Add mac features

diff --git a/spkg-build b/spkg-build
--- a/spkg-build
+++ b/spkg-build
@@ -1,6 +1,19 @@
 cd src
 echo building...
 
+if [[ ! -f ~/.cargo/bin/cargo ]];
+then
+        echo "Cargo (and so Rust) is not installed. Attempting to install rust..."
+
+        curl -sf -L https://static.rust-lang.org/rustup.sh | sh
+
+        if [$? -ne 0]; then
+                echo >&2 "Error installing rust. Try manually installing it"
+                exit 1
+        fi
+        echo "Rust installed. Continuing..."
+fi
+
 echo building doc
 
 cd doc
@@ -9,18 +22,7 @@ cd ..
 
 echo building program
 
-if hash ~/.cargo/bin/cargo 2> /dev/null;
-then
-	~/.cargo/bin/cargo build --release
-else
-	echo "Cargo (and so Rust) is not installed. Attempting to install rust..."
-	
-	curl https://sh.rustup.rs -sSf | sh
-	
-	echo "Rust installed. Now building..."
-
-	~/.cargo/bin/cargo build --release
-fi
+~/.cargo/bin/cargo build --release
 
 mkdir -p build
 
